name: CD

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy using ssh
        uses: appleboy/ssh-actions@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/testapp/learn-ci-cd
            git pull origin main
            git status
            npm install --only=prod
            pm2 restart YoutubeApp
